### ISSUE TITLE
Make hover more like a full blown highlight

### ISSUE THREAD

**Issue by beaufortfrancois** [beaufortfrancois/polymer-ready-chrome-extension#1]
From https://chrome.google.com/webstore/detail/polymer-ready/aaifiopbmiecbpladpjaoemohhfjcbdk/reviews,

_I love this extension! Great idea. I would recommend making the highlight that appears as a dashed rectangle around components when you hover over them in the menu a little more obvious however - it is difficult to see/notice on some components. Maybe a full blown highlight (similar to how the magnifying glass in the Chrome Developer Tools works) would be easier to use?_

**Comment by ebidel** [comment]
+1 from me. It's really hard to see the dotted box around highlighted elements. Maybe a tinted background highlight like https://gist.github.com/ebidel/4bdbe9db55d8a775d0a4#file-highlight_custom_elements-js-L17?

**Comment by beaufortfrancois** [comment]
I've added a tinted background (https://github.com/beaufortfrancois/polymer-ready-chrome-extension/commit/51cdd14b4d71811aa78ac109e081951b023e82f3) as suggested and just published an update to the extension at https://chrome.google.com/webstore/detail/aaifiopbmiecbpladpjaoemohhfjcbdk.

Thanks again ;)

**Comment by ebidel** [comment]
Sweet! Thanks
