### ISSUE TITLE
Make each item toggleable

### ISSUE THREAD

**Issue by AaronLayton** [beaufortfrancois/polymer-ready-chrome-extension#10]
As title - I think it would be more useful to toggle the highlighting if you click it, have the hover effect aswell though ;-)

**Comment by beaufortfrancois** [comment]
Thanks Aaron!
I've updated Polymer Ready extension (https://github.com/beaufortfrancois/polymer-ready-chrome-extension/commit/5e55f7fa8456e810dd52ca9a6cab1af54264225d) and pushed it to the Web Store. You should receive it soon now.

**Comment by AaronLayton** [comment]
Got it and works great thanks ;-0
