### ISSUE TITLE
does not work on the classic shop demo for me

### ISSUE THREAD

**Issue by joeblew99** [beaufortfrancois/polymer-ready-chrome-extension#13]
https://github.com/Polymer/shop

Just does not register that localhost:8080 is a web site uisng polymer elements.

any ideas ?

This is a really useful tool to me, because its very hard to visualise where on the web page a component is used when programming in polymer. In the IDE, the elements are not nested in folders to represent the actual mediator pattern nesting we all use.
SO this is a really useful tool to me.

**Comment by beaufortfrancois** [comment]
I believe this happens because https://shop.polymer-project.org/ doesn't set `window.WebComponents`. Maybe @ebidel or @robdodson can chime in and help us understand why.

This content script simply shows page action when:

```js

window.addEventListener('polymer-ready', showPageAction);
window.addEventListener('WebComponentsReady', showPageAction);

**Comment by joeblew99** [comment]
@beaufortfrancois 
He commented here.. Not a solution, just a good option
https://groups.google.com/forum/?fromgroups=#!topic/polymer-dev/vw-SpbE9wHw

@ebidel

**Comment by ebidel** [comment]
`window.WebComponents` only gets set if you load the polyfills. I believe shop feature detects loading the polyfills.

**Comment by abdonrd** [comment]
@ebidel yes, it does: https://github.com/Polymer/shop/blob/master/index.html#L62-L73

**Comment by joeblew99** [comment]
@ebidel @abdonrd 

in the index.html of the shop demo i tried commenting out all the script:
<script>
    /*window.performance && performance.mark && performance.mark('index.html');

    Polymer = {lazyRegister: true, dom: 'shadow'};

    (function() {
      if ('registerElement' in document
          && 'import' in document.createElement('link')
          && 'content' in document.createElement('template')) {
        // platform is good!
      } else {
        // polyfill the platform!
        var e = document.createElement('script');
        e.src = '/bower_components/webcomponentsjs/webcomponents-lite.min.js';
        document.body.appendChild(e);
      }
    })();
    */
  </script>


It made no difference to the application (bundled or not) OR to the issue of the polymer red extension not working. I was just trying things to see what worked as i am still learning the new polymer

**Comment by beaufortfrancois** [comment]
Loading manually polyfills from DevTools console actually shows chrome extension page action as you can see below.

![screenshot 2016-07-27 at 8 47 27 am](https://cloud.githubusercontent.com/assets/634478/17166363/d814fa10-53d6-11e6-8ce5-d438bb2b498a.png)

Now, what we need to figure out is how to detect Polymer when polyfills are not loaded.

@ebidel We're in the context of the chrome extension content script, which means we cannot use variables or functions defined by web pages or by other content scripts (eg. `Polymer.whenReady` is not an option there.)

For info, we already talked about this at https://github.com/beaufortfrancois/polymer-ready-chrome-extension/issues/9

**Comment by ebidel** [comment]
The only other thing I can think of is to scrape the page for custom elements and check for properties that Polymer puts on the DOM elements. That would require running extension code on every page though :(

**Comment by beaufortfrancois** [comment]
@ebidel do you know why `PolymerReady` event is not fired anymore in polymer 1?

**Comment by ebidel** [comment]
`polymer-ready` was removed.

**Comment by ebidel** [comment]
Sites that lazy load the polyfills really need to adopt [this pattern](https://gist.github.com/ebidel/1d5ede1e35b6f426a2a7#file-wcr_lazyload-html-L20-L27). e.g. fire the `WebComponentsReady` event themselves.

**Comment by ebidel** [comment]
Found something that might work as a backup. The `dom-change` event fires when `<template dom-if/repeat/dom-bind>` fires. That will be for a lot of elements, but it's not guaranteed if people aren't using those elements. I did check shop and chromestatus, which do trigger it. 

```
document.addEventListener('dom-change', function onDomChange(e) {
  document.removeEventListener('dom-change', onDomChange);
});
```

**Comment by beaufortfrancois** [comment]
Thank you so much @ebidel! This is definitely an improvement as it also fixes https://github.com/beaufortfrancois/polymer-ready-chrome-extension/issues/9 where https://gaming.youtube.com/ wasn't showing the page action either.

I've included your fix at https://github.com/beaufortfrancois/polymer-ready-chrome-extension/commit/e97c0943cc1d8344d73f0541086fdb793aef7528 and pushed an update for the chrome extension. See https://chrome.google.com/webstore/detail/aaifiopbmiecbpladpjaoemohhfjcbdk

**Comment by abdonrd** [comment]
@beaufortfrancois I still see the version 0.8 in the Chrome Web Store:

<img width="977" alt="screen shot 2016-07-28 at 09 32 30" src="https://cloud.githubusercontent.com/assets/1007051/17204540/6510e9ea-54a6-11e6-8454-fe726e99d487.png">

**Comment by beaufortfrancois** [comment]
@abdonrd You may want to wait an hour to see the published item. Please let me know when you see it.

**Comment by abdonrd** [comment]
@beaufortfrancois okey, thanks! :)

**Comment by abdonrd** [comment]
@beaufortfrancois now updated.

And yay! It works with all projects listed here: [abdonrd/PolymerProjects](https://github.com/abdonrd/PolymerProjects).

**Comment by beaufortfrancois** [comment]
Woohoo!
