### ISSUE TITLE
Update elements.polymer-project.org to webcomponents.org

### ISSUE THREAD

**Issue by abdonrd** [beaufortfrancois/polymer-ready-chrome-extension#17]
I propose update the links.

From: [elements.polymer-project.org](https://elements.polymer-project.org)
To: [webcomponents.org: PolymerElements](https://www.webcomponents.org/collection/Polymer/elements)

**Comment by beaufortfrancois** [comment]
Argh you're right we should do this.
From what I can see, it is not straightforward as https://elements.polymer-project.org/catalog.json doesn't exist per say in https://www.webcomponents.org/api/...

@dstockwell might help us there.
Do you know a way to retrieve all web components from this API?
I fail to see how by reading https://github.com/webcomponents/webcomponents.org/blob/master/src/api.py#L632-L649

**Comment by dstoc** [comment]
> @dstockwell might help us there.
> Do you know a way to retrieve all web components from this API?

All polymer elements?

You can use the search API to get a paged view of all repos:
https://www.webcomponents.org/api/search/owner:PolymerElements

And then use the docs API to drill down to `elementsByTagName`:
https://www.webcomponents.org/api/docs/PolymerElements/paper-card

But that's going to be a lot of requests 😢
