### ISSUE TITLE
Support polymer 1.0

### ISSUE THREAD

**Issue by ebidel** [beaufortfrancois/polymer-ready-chrome-extension#8]
In 1.0, the `polymer-ready` event is no longer fired. `WebComponentsReady` is the recommended event now. However, you don't have to be using polymer (just the polyfills) to fire that event.

I recommend:
1. wait for `WebComponentsReady`
2. Check that `window.Polymer` is defined on the page. If so, Polymer is being used.
3. then, for all the custom elements on the page, check if `Polymer.DomModule.import(el.localName)` returns a `dom-module`. If it returns `null`, the element wasn't defined by polymer 1.0.

It would still be nice to support 0.5 users. That should be pretty harmless if you still wait for `polymer-ready` and refactor some logic to support 0.5 and 1.0 checks.

**Comment by beaufortfrancois** [comment]
Thanks Eric,

I've recently added basic polymer 1.0 support by checking `WebComponentsReady` fired event (https://github.com/beaufortfrancois/polymer-ready-chrome-extension/commit/21c79dca5737af604b8a12aa2d55726748c43245)
It should work on https://elements.polymer-project.org/ for instance. Let me know if that's good for you.

**Comment by beaufortfrancois** [comment]
(gentle ping @ebidel)

**Comment by ebidel** [comment]
+1 sorry I missed this. Working great on 0.5 apps and 1.0 apps.
