### ISSUE TITLE
YouTube Gaming is using Polymer, but the icon does not appear

### ISSUE THREAD

**Issue by abdonrd** [beaufortfrancois/polymer-ready-chrome-extension#9]
Why is that? :open_mouth: 

Link: https://gaming.youtube.com

**Comment by beaufortfrancois** [comment]
That's a good question ;(
@addyosmani Would you know why the `WebComponentsReady` event is not fired at https://gaming.youtube.com?

**Comment by abdonrd** [comment]
I prefer write here instead of create another issue...
I have another problem with Github. They use a Web Components like <time>, <g-emoji>, etc. But it isn't created with Polymer.

**Comment by addyosmani** [comment]
As long as they're loading in the Web Component polyfills, the event should absolutely be getting fired. There may be a chance they're trying to conditionally load up the polyfills (that has a small chance of impacting this). I won't have time to dig into it this week, but I would probably look at https://gaming.youtube.com/s/gaming/47cacffd/gaming_polymer.js where they appear to be sniffing for those events.

**Comment by alexpaluzzi** [comment]
@addyosmani is right, but it happens before `gaming_polymer.js`, here: https://s.ytimg.com/yts/jsbin/html5player-new-en_US-vflOWWv0e/html5player-new.js

I had a few minutes to try and waddle through obfuscated code, but I can see that this function is not being called in Chrome, but it is in other browsers:
```
C$.B = function(a, b) {
        gw("pwc");
        var c = document.querySelector(a);
        document.registerElement(a, {});
        var d = c.querySelector("template")
          , c = c.createShadowRoot()
          , d = document.importNode(d.content, !0);
        c.appendChild(d);
        c = c.getElementById(b);
        d = t("ytplayer.config");
        c = C$.create(c, d);
        d.loaded = !0;
        return c
};
```
The `WebComponentsReady` event is firing from here, so it is definitely the culprit.

**Comment by beaufortfrancois** [comment]
It looks like the only way to detect these web components would be to parse all HTML elements once `load` event has been fired. And I really don't like that ;(

```javascript
window.addEventListener('load', function() {                                                                                                                                   
  var customElements = Array.prototype.slice.call(document.querySelectorAll('* /deep/ *')).filter(function(element) {                                                              
    return element.localName.indexOf('-') != -1 || element.getAttribute('is');                                                                                                 
  });                                                                                                                                                                          
  if (customElements.length) {                                                                                                                                                 
    showPageAction();                                                                                                                                                          
  }                                                                                                                                                                            
});  
```

Any suggestions?

**Comment by ebidel** [comment]
I believe it also doesn't fire if you load it async. At least that was my experience before. We may have fixed that since. Although, the extension doesn't work on https://poly-mail.appspot.com, which loads the polyfills dynamically.

However, it looks like gaming.youtube.com is conditionally loading the polyfill on the server based on the browser. If FF `window.WebComponents`  is there. Chrome, it's not.

You could see if `Polymer.whenReady(function() {})` gets called. Although that will be tricky, as you have to wait for that method to be defined before dropping it into the page. You could also wait for `HTMLImportsLoaded`.

3rd option is to be more aggressive:
```
if (window.WebComponents) {
addEventListener('WebComponentsReady', ready);
} else {
if (document.readyState === 'interactive' || document.readyState === 'complete') {
ready()
} else {
addEventListener('DOMContentLoaded', ready);
```

**Comment by alexpaluzzi** [comment]
I think it might be worth looking at the `Polymer.whenReady` option.

Correct me if I'm wrong, but the 3rd option there will only let us know if they are polyfilling the web components right? We want to identify Polymer, not `webcomponents.js`.

**Comment by ebidel** [comment]
Correct. You'd have to modify the snippets to detect Polymer, not WC. Just throwing it out there as a possible way to go about it.

**Comment by beaufortfrancois** [comment]
Even though content scripts run in the context of web pages, they cannot use variables or functions defined by web pages or by other content scripts. This means `Polymer.whenReady` is not an option there.

**Comment by abdonrd** [comment]
Any news about this? :smile:

**Comment by beaufortfrancois** [comment]
Nope ;(
I can't think of a nice way of handling this sadly.

Keeping this issue opened though in case someone has an idea there.

**Comment by abdonrd** [comment]
Only for add information, another web that use Polymer and the icon not appear:

https://music.youtube.com

**Comment by abdonrd** [comment]
More information:

The extension detects x-tag elements like Polymer elements: http://x-tag.github.io

**Comment by abdonrd** [comment]
Another example: https://poly-icon.appspot.com

**Comment by beaufortfrancois** [comment]
As said in https://github.com/beaufortfrancois/polymer-ready-chrome-extension/issues/9#issuecomment-136678554, I can't think of a way to reliably detect Polymer Elements for now ;(

**Comment by abdonrd** [comment]
Thanks @beaufortfrancois! I just add more examples to have more information when checking. :sweat_smile: 

Maybe you can check if there are a global `Polymer` object?

**Comment by beaufortfrancois** [comment]
I don't have access to the DOM `Polymer` Object from an injected script point of view sadly.

**Comment by beaufortfrancois** [comment]
Thanks to @ebidel, this issue is fixed. See https://github.com/beaufortfrancois/polymer-ready-chrome-extension/issues/13#issuecomment-235654565

**Comment by abdonrd** [comment]
Yay! Thanks @beaufortfrancois and @ebidel! 🎉
